# Generated by Django 4.1.4 on 2022-12-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='loan_balance',
            field=models.IntegerField(default=1000000),
        ),
    ]
