# Generated by Django 4.1.4 on 2022-12-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_info_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='micromorts',
            field=models.IntegerField(default=2),
        ),
    ]
