# Generated by Django 4.1.4 on 2022-12-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_info_micromorts'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='profession',
            field=models.CharField(choices=[('OF', 'Office'), ('PY', 'Freshman'), ('FI', 'Sophomore'), ('DR', 'Junior'), ('FO', 'Senior'), ('BU', 'Graduate'), ('SE', 'Seaman'), ('CA', 'Caster'), ('WO', 'Wooder'), ('SH', 'Shahter'), ('FE', 'Fermer')], default='OF', max_length=2),
        ),
    ]
