# Generated by Django 4.1.4 on 2022-12-11 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_info_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='profession',
        ),
    ]
