# Generated by Django 4.1.4 on 2022-12-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_info_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='hobby',
            field=models.CharField(choices=[('91.2', 'Бейсджампинг'), ('27.3', 'Автогонки'), ('4.8', 'Дельтаплан'), ('2.7', 'Мотогонки'), ('1.5', 'Альпинизм'), ('1.2', 'Бокс и ММА'), ('0.27', 'Каякинг'), ('0.17', 'Треккинг/Велосипедный спорт'), ('0.08', 'Дайвинг'), ('0.02', 'Парашютный спорт'), ('0', 'Другое')], default=0, max_length=250),
        ),
    ]
