# Generated by Django 4.1.4 on 2022-12-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_info_alcogol_info_cigarets'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='obrabotka',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='info',
            name='micromorts',
            field=models.IntegerField(default=0),
        ),
    ]
