# Generated by Django 4.1.4 on 2022-12-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_info_micromorts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='alcogol',
            field=models.TextField(default=0),
        ),
    ]
